### ISSUE TITLE
Move into `skeletal_animation` project

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/skeletal_animation_demo#34]
Doesn't make sense to have it as a separate repo

**Comment by bvssvni** [comment]
Remember to add an `exclude` flag to make Cargo not upload this project to crates.io.

I think it makes a bit sense to keep them separated, because you can fork this project and modify it without needing to remove the library.

**Comment by kvark** [comment]
@bvssvni if it's just an example inside the library crate, I don't think cargo will upload it.

> because you can fork this project and modify it without needing to remove the library

Yes, I agree that a separate project is friendlier for newcomers if they need something to start with.

**Comment by bvssvni** [comment]
It's not a big deal for me to keep it updated because of Eco. Closing?
