### ISSUE TITLE
Loading takes almost 2 min

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/skeletal_animation_demo#6]
I timed how long it took before I got a picture:

```
$ time cargo run
     Running `target/debug/demo`

real    1m49.927s
user    1m47.046s
sys 0m1.565s
```

**Comment by stjahns** [comment]
Running in release mode helps a lot, almost instant on my desktop machine. Texture::from_path is the bottleneck by far, looks the png decompression stuff runs pretty slow in debug mode, and one of the textures is about 5 MB.

**Comment by bvssvni** [comment]
Yeah, that made a huge difference:

```
$ time cargo run --release
     Running `target/release/demo`

real    0m7.078s
user    0m4.872s
sys 0m1.432s
```
